// Generated by dts-bundle-generator v9.5.1

import { EditorView } from '@codemirror/view';
import { ReactNode } from 'react';
import { Root } from 'react-dom/client';
import { Layout } from 'react-resizable-panels';

/**
 * @file Events.ts
 * @description Lightweight, decoupled event emitter and subscription token implementation.
 *
 * Used as the fundamental pub/sub communication bus across the core kernel (`App.events`),
 * layout hierarchy (`Workspace`, `WorkspaceLeaf`, `WorkspaceTabs`), and storage layer (`Vault`).
 */
/**
 * Token returned from `on()` enabling safe deregistration via `offref()`.
 */
export declare class EventRef {
	readonly event: string;
	readonly handler: (...args: any[]) => any;
	readonly e: Events;
	constructor(event: string, handler: (...args: any[]) => any, emitter: Events);
}
/**
 * Base EventEmitter class for Resin subsystems.
 */
export declare class Events {
	private listeners;
	/**
	 * Subscribes a listener to an event.
	 *
	 * @param {string} event - Event name.
	 * @param {(...args: any[]) => any} handler - Callback function.
	 * @param {any} [ctx] - Optional this context to bind.
	 * @returns {EventRef} Subscription token used to unsubscribe.
	 */
	on(event: string, handler: (...args: any[]) => any, ctx?: any): EventRef;
	/**
	 * Unsubscribes a listener by function reference.
	 *
	 * @param {string} event - Event name.
	 * @param {(...args: any[]) => any} handler - Callback function.
	 */
	off(event: string, handler: (...args: any[]) => any): void;
	/**
	 * Unsubscribes a listener by its subscription token (`EventRef`).
	 *
	 * @param {EventRef} ref - Subscription token returned from `on()`.
	 */
	offref(ref: EventRef): void;
	/**
	 * Synchronously emits an event to all registered listeners.
	 *
	 * @param {string} event - Event name.
	 * @param {...any[]} args - Arguments passed to listeners.
	 */
	emit(event: string, ...args: any[]): void;
}
declare class Lifecycle {
	/**
	 * Invoked when the object is initialized, loaded, or mounted.
	 */
	onLoad(): Promise<void>;
	/**
	 * Invoked when the object is destroyed, unloaded, or unmounted.
	 */
	onUnload(): Promise<void>;
}
declare abstract class Component extends Lifecycle {
	private _cleanups;
	private _children;
	/**
	 * Registers an event listener subscription that is automatically unregistered upon plugin unload.
	 *
	 * @param {EventRef} eventRef - Subscription token returned from `events.on()`.
	 */
	registerEvent(eventRef: EventRef): void;
	/**
	 *
	 * @param fn callback to be executed on unload
	 */
	register(fn: () => void): void;
	addChild(child: Component): void;
	removeChild(child: Component): void;
	/**
	 * @description registers a {@link window.setInterval} to be cleaned up on unload
	 * @param id - id of interval to cleanup
	 * @returns id of registered interval
	 */
	registerInterval(id: number): number;
	registerDomEvent<K extends keyof HTMLElementEventMap>(el: HTMLElement | Window | Document, type: K, callback: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
	onUnload(): Promise<void>;
}
/**
 * Abstract base class for all workspace views.
 */
export declare abstract class View extends Component {
	/** Reference to the WorkspaceLeaf slot hosting this view */
	readonly leaf: WorkspaceLeaf;
	/** Root DOM container element for the view's rendered output */
	readonly containerEl: HTMLElement;
	private _reactRoot;
	private _svelteInstance;
	constructor(leaf: WorkspaceLeaf);
	private _app;
	/** Central App instance accessed via the host leaf */
	get app(): App;
	set app(val: any);
	/**
	 * Mounts or updates a React component tree inside the view container.
	 * Automatically wraps with AppContext.Provider and handles lifecycle cleanup.
	 *
	 * @param {ReactNode} element - React element to render.
	 * @param {HTMLElement} [targetEl] - Target container element (defaults to `this.containerEl`).
	 * @returns {Root} React root instance.
	 */
	renderReact(element: ReactNode, targetEl?: HTMLElement): Root;
	/**
	 * Mounts a Svelte 5 component inside the view container.
	 * Automatically passes `{ app, leaf }` in props and handles lifecycle cleanup.
	 *
	 * @param {any} Component - Svelte component class.
	 * @param {Record<string, any>} [props={}] - Additional component props.
	 * @param {HTMLElement} [targetEl] - Target container element (defaults to `this.containerEl`).
	 * @returns {any} Mounted Svelte component instance.
	 */
	renderSvelte<T = any>(Component: any, props?: Record<string, any>, targetEl?: HTMLElement): T;
	/** Returns unique view type identifier (e.g. 'editor', 'welcome') */
	abstract getViewType(): string;
	/** Returns human-readable label for tab header */
	abstract getDisplayText(): string;
	/** Returns Phosphor icon name for tab header */
	getIcon(): string;
	/** Serializes view-specific state for layout persistence */
	getState(): any;
	/** Hydrates view with persisted state */
	setState(_state: any): Promise<void>;
	/** Retrieves ephemeral runtime UI state */
	getEphemeralState(): any;
	/** Restores ephemeral runtime UI state */
	setEphemeralState(_state: any): void;
	/** Invoked when the view is mounted into the DOM */
	onLoad(): Promise<void>;
	/** Invoked when the view is destroyed or unmounted */
	onUnload(): Promise<void>;
	/** Invoked when the leaf containing this view gains focus/activation */
	onActivate(): void;
	/** Invoked when the leaf containing this view loses focus */
	onDeactivate(): void;
	/** Invoked when the hosting leaf is resized */
	onResize(): void;
}
/** Factory function creating a new View instance for a given leaf */
export type ViewCreator = (leaf: WorkspaceLeaf) => View;
/** View registration record stored in App.viewRegistry */
export interface ViewRegistration {
	creator: ViewCreator;
	icon: string;
	title: string;
}
export declare class WorkspaceLeaf extends Events {
	/** Unique leaf identifier */
	readonly id: string;
	/** Active view type string (e.g. 'editor', 'empty', 'welcome') */
	private _type;
	/** Persisted view configuration/state (e.g. `{ path: 'notes/test.md' }`) */
	private _state;
	/** Ephemeral runtime UI state not persisted to disk */
	private ephemeral;
	/** Active mounted View instance */
	view: View;
	/** Parent tab group */
	parent: any;
	/** Reference to central App instance */
	private _app;
	get app(): any;
	set app(val: any);
	constructor(id: string);
	/**
	 * Mounts a new View instance into this leaf, unloading any previous view.
	 *
	 * @param {View} view - The new View instance to mount.
	 */
	open(view: View): Promise<void>;
	/**
	 * Returns temporary runtime UI state (scroll position, selections).
	 */
	getEphemeralState(): any;
	/**
	 * Updates temporary runtime UI state.
	 */
	setEphemeralState(state: any): void;
	/**
	 * Serializes the leaf into a JSON-compatible object for layout saving.
	 */
	serialize(): {
		id: string;
		type: string;
		state: any;
	};
	toJSON(): {
		id: string;
		type: string;
		state: any;
	};
	/**
	 * Rehydrates a WorkspaceLeaf from a serialized layout object.
	 *
	 * @param {any} data - Serialized leaf object.
	 * @returns {WorkspaceLeaf} Hydrated leaf instance.
	 */
	static hydrate(data: any): WorkspaceLeaf;
	/**
	 * Returns the icon name associated with this leaf's active view.
	 */
	getIcon(): string;
	/**
	 * Resolves the human-readable tab title for the UI.
	 * Prioritizes clean note file names for editor tabs and view display text for custom views.
	 */
	getTitle(): string;
	/**
	 * Returns the view type string of this leaf.
	 */
	getType(): string;
	/**
	 * Retrieves the current view state container.
	 */
	getViewState(): {
		type: string;
		state: any;
	};
	/**
	 * Updates the leaf's view type and state, notifying listeners and refreshing the view.
	 *
	 * @param {{ type: string; state?: any }} viewState - New type and state payload.
	 */
	setViewState(viewState: {
		type: string;
		state?: any;
	}): Promise<void>;
	/**
	 * Detaches and closes this leaf from the workspace.
	 */
	detach(): void;
}
declare class WorkspaceItem extends Events {
}
declare class WorkspaceParent extends WorkspaceItem {
}
export declare class WorkspaceTabs extends Events {
	/** Unique tab group identifier */
	readonly id: string;
	/** Array of workspace leaves attached to this tab group */
	private leaves;
	/** ID of the currently active/focused leaf */
	private activeId;
	/** Parent split node containing this tab group */
	readonly parent: WorkspaceSplit;
	constructor(id: string, parent: WorkspaceSplit);
	/**
	 * Atomically creates, initializes, and appends a new `WorkspaceLeaf` to this tab group.
	 *
	 * @param {boolean} [activate=true] - Whether to immediately activate the newly created leaf.
	 * @param {string} [type='empty'] - View type to initialize the leaf with.
	 * @param {any} [state={}] - Initial view state payload.
	 * @returns {WorkspaceLeaf} The created leaf instance.
	 */
	createLeaf(activate?: boolean, type?: string, state?: any): WorkspaceLeaf;
	/**
	 * Adds an existing `WorkspaceLeaf` instance to this tab group.
	 *
	 * @param {WorkspaceLeaf} leaf - The leaf to add.
	 * @param {boolean} [activate=false] - Whether to activate it.
	 */
	addLeaf(leaf: WorkspaceLeaf, activate?: boolean): void;
	/**
	 * Serializes the tab group state for layout persistence.
	 */
	serialize(): {
		id: string;
		activeId: string;
		leaves: {
			id: string;
			type: string;
			state: any;
		}[];
	};
	toJSON(): {
		id: string;
		activeId: string;
		leaves: {
			id: string;
			type: string;
			state: any;
		}[];
	};
	/**
	 * Hydrates a `WorkspaceTabs` instance from a serialized object.
	 *
	 * @param {any} data - Serialized tab group object.
	 * @param {WorkspaceSplit} parent - Parent split node.
	 * @returns {WorkspaceTabs} Hydrated instance.
	 */
	static hydrate(data: any, parent: WorkspaceSplit): WorkspaceTabs;
	/**
	 * Activates a leaf within this tab group by its ID.
	 * Emits `tabs:activated`.
	 *
	 * @param {string} id - Leaf unique identifier.
	 */
	activateLeaf(id: string): void;
	/**
	 * Removes a leaf from this tab group by its ID.
	 * If the active leaf was removed, activates the last remaining leaf or emits `tabs:empty`.
	 *
	 * @param {string} id - Leaf unique identifier.
	 */
	removeLeaf(id: string): void;
	/**
	 * Inserts a leaf at a specific index in this tab group.
	 *
	 * @param {WorkspaceLeaf} leaf - Leaf instance to insert.
	 * @param {number} index - Position index.
	 * @param {boolean} [activate=false] - Whether to activate the inserted leaf.
	 */
	insertLeaf(leaf: WorkspaceLeaf, index: number, activate?: boolean): void;
	/**
	 * Reorders leaves within this tab group from one index to another.
	 *
	 * @param {number} fromIndex - Source index.
	 * @param {number} toIndex - Destination index.
	 */
	reorderLeaf(fromIndex: number, toIndex: number): void;
	/**
	 * Finds the index of a leaf in this tab group.
	 */
	findLeafIndex(id: string): number;
	/**
	 * Removes a leaf from this tab group without destroying it (for transferring between tabs).
	 */
	extractLeaf(id: string): WorkspaceLeaf | null;
	/**
	 * Returns the currently active leaf in this tab group, or null if empty.
	 */
	getActiveLeaf(): WorkspaceLeaf | null;
	/**
	 * Returns a shallow copy of all leaves in this tab group.
	 */
	getLeaves(): WorkspaceLeaf[];
}
declare class WorkspaceSplit extends WorkspaceParent {
	/** Unique split identifier */
	id: string;
	/** Parent split node or null if this is the root */
	parent: WorkspaceParent | null;
	/** Child split nodes or tab groups */
	children?: (WorkspaceSplit | WorkspaceTabs)[];
	/** Split layout orientation */
	direction: "horizontal" | "vertical";
	/** Resizable panel dimension percentages */
	private sizes;
	constructor(parent: WorkspaceParent | null, direction: "horizontal" | "vertical");
	/**
	 * Splits an existing leaf's parent tab group in the given direction.
	 *
	 * @param {WorkspaceLeaf} leaf - Target leaf to split alongside.
	 * @param {'horizontal' | 'vertical'} direction - Split direction.
	 */
	splitLeaf(leaf: WorkspaceLeaf, direction: "horizontal" | "vertical"): void;
	/**
	 * Recursively executes a callback on every `WorkspaceLeaf` descending from this split node.
	 *
	 * @param {(leaf: WorkspaceLeaf) => void} cb - Leaf visitor callback.
	 */
	iterateLeaves(cb: (leaf: WorkspaceLeaf) => void): void;
	/**
	 * Serializes this split node and all descendants for layout persistence.
	 */
	serialize(): {
		id: string;
		direction: "horizontal" | "vertical";
		sizes: Layout;
		children: any[];
	};
	toJSON(): {
		id: string;
		direction: "horizontal" | "vertical";
		sizes: Layout;
		children: any[];
	};
	/**
	 * Hydrates a `WorkspaceSplit` from a serialized layout tree.
	 *
	 * @param {any} data - Serialized split data.
	 * @param {WorkspaceParent | null} parent - Parent node reference.
	 * @returns {WorkspaceSplit} Hydrated split instance.
	 */
	static hydrate(data: any, parent: WorkspaceParent | null): WorkspaceSplit;
	/**
	 * Recursively locates the parent `WorkspaceTabs` holding the specified leaf.
	 */
	findTabsByLeaf(leaf: WorkspaceLeaf): WorkspaceTabs | null;
	/**
	 * Recursively finds a `WorkspaceTabs` group by its ID.
	 */
	findTabsById(id: string): WorkspaceTabs | null;
	/**
	 * Finds the first descendant `WorkspaceTabs` group in depth-first order.
	 */
	findFirstTabs(): WorkspaceTabs | null;
	/**
	 * Appends a child split or tabs group.
	 */
	addChild(child: WorkspaceSplit | WorkspaceTabs): void;
	/**
	 * Swaps two child nodes and their corresponding layout size allocations.
	 */
	swapChild(a: WorkspaceSplit | WorkspaceTabs, b: WorkspaceSplit | WorkspaceTabs): void;
	/**
	 * Replaces an existing child node with a new child node.
	 */
	replaceChild(old: WorkspaceSplit | WorkspaceTabs, next: WorkspaceSplit | WorkspaceTabs): void;
	/**
	 * Adjusts the percentage size allocation for a specific child index.
	 */
	resize(index: number, percentage: number): void;
	/** Returns current layout size percentage map */
	getSizes(): Layout;
	/** Sets the layout size percentage map */
	setSizes(layout: Layout): void;
	/** Returns direct children array */
	getChildren(): (WorkspaceTabs | WorkspaceSplit)[] | undefined;
}
declare class WorkspaceSplitSide extends WorkspaceSplit {
	/** Sidebar width percentage (e.g. '20') */
	private size;
	/** Whether this sidebar is currently collapsed */
	private collapsed;
	/** Collapses the sidebar */
	collapse(): void;
	/** Expands the sidebar */
	expanded(): void;
	/** Toggles sidebar between collapsed and expanded states */
	toggle(): void;
	/** Returns true if the sidebar is currently collapsed */
	isCollapsed(): boolean;
	/** Serializes the sidebar layout and collapsed state */
	serialize(): any;
	toJSON(): any;
	/**
	 * Hydrates a `WorkspaceSplitSide` from a serialized layout object.
	 *
	 * @param {any} data - Serialized sidebar object.
	 * @returns {WorkspaceSplitSide} Hydrated sidebar instance.
	 */
	static hydrate(data: any): WorkspaceSplitSide;
	/** Returns the configured sidebar width percentage */
	getSize(): string;
	/** Sets the configured sidebar width percentage */
	setSize(size: string): void;
}
/**
 * Human friendly position contrary to codemirrors character offset
 */
export interface EditorPosition {
	/**
	 * 0-indexed line number
	 */
	line: number;
	/**
	 * 0-indexed character offset within the line
	 */
	ch: number;
}
export interface EditorRange {
	from: EditorPosition;
	to: EditorPosition;
}
export declare class Editor {
	readonly cm: EditorView;
	constructor(cm: EditorView);
	/**
	 * This function converts EditorPosition (pos, col) to codemirrors native char offset
	 * @param pos Position in editor to convert
	 * @returns converted pos to codemirrors character offset
	 */
	posToOffset(pos: EditorPosition): number;
	offsetToPos(offset: number): EditorPosition;
	getValue(): string;
	getLine(line: number): string;
	lineCount(): number;
	getRange(from: EditorPosition, to: EditorPosition): string;
	getCursor(): EditorPosition;
	setCursor(pos: EditorPosition): void;
	getSelection(): string;
	replaceSelection(replacement: string): void;
	replaceRange(replacement: string, from: EditorPosition, to?: EditorPosition): void;
	setLine(line: number, text: string): void;
}
/**
 * Configuration options passed to `Workspace.openFile`.
 */
export interface OpenFileOptions {
	/** Whether the opened leaf should be activated immediately (defaults to true) */
	active?: boolean;
	/** Force creation of a brand new tab even if an empty tab exists (defaults to false) */
	newTab?: boolean;
	/** Target specific leaf instance or leaf ID to replace in-place */
	leaf?: WorkspaceLeaf | string;
	/** Target split area ('main' | 'left' | 'right') */
	split?: "main" | "left" | "right";
}
export declare class Workspace extends Events {
	/** Default fallback layout structure if workspace.json is absent */
	private WORKSPACE_DEFAULT;
	private history;
	private vaultRoot;
	private workspaceJSONPath;
	private layoutReady;
	private layoutReadyCallbacks;
	/** Collapsible left sidebar hierarchy */
	left: WorkspaceSplitSide;
	/** Central multi-split layout tree */
	main: WorkspaceSplit;
	/** Collapsible right panel hierarchy */
	right: WorkspaceSplitSide;
	/** Reference to central App instance */
	private _app;
	get app(): any;
	set app(instance: any);
	/**
	 * Recursively executes a callback on every active WorkspaceLeaf in the workspace.
	 */
	iterateLeaves(callback: (leaf: WorkspaceLeaf) => void): void;
	/** Internal active workspace leaf reference */
	private _activeLeaf;
	private saveTimeout;
	constructor(vaultRoot: string);
	/**
	 * Function you can use to register a callback to run after workspace has mounted
	 * @param callback function you want to run immediately when layout finished mounting
	 */
	onLayoutReady(callback: () => void): void;
	/**
	 * Function that you can use to get current layout mounting status
	 * @returns whether layout finished mounting or no
	 */
	isLayoutReady(): boolean;
	/**
	 * gives you instance of class Editor that's currently active
	 */
	get activeEditor(): Editor | null;
	/**
	 * Currently active/focused WorkspaceLeaf across the entire workspace.
	 * Resolves the explicitly activated leaf or falls back to the active tab in the main split.
	 */
	get activeLeaf(): WorkspaceLeaf | null;
	/**
	 * Explicitly sets the active workspace leaf and notifies listeners.
	 *
	 * @param {WorkspaceLeaf | null} leaf - The leaf to activate.
	 * @param {{ pushHistory?: boolean; focus?: boolean }} [options] - Options for history and focus.
	 */
	setActiveLeaf(leaf: WorkspaceLeaf | null, options?: {
		pushHistory?: boolean;
		focus?: boolean;
	}): void;
	/**
	 * Retrieves the active workspace leaf.
	 *
	 * @returns {WorkspaceLeaf | null}
	 */
	getActiveLeaf(): WorkspaceLeaf | null;
	/**
	 * Retrieves the active leaf only if it matches the specified view type.
	 *
	 * @param {string} type - View type string (e.g. 'editor', 'file-explorer').
	 * @returns {WorkspaceLeaf | null}
	 */
	getActiveLeafOfType(type: string): WorkspaceLeaf | null;
	/**
	 * Retrieves the vault-relative file path of the currently active editor leaf, if any.
	 *
	 * @returns {string | null}
	 */
	getActiveFile(): string | null;
	/**
	 * Asynchronously creates and initializes a Workspace instance, hydrating the layout tree from disk.
	 *
	 * @param {string} vaultRoot - Absolute path to the vault folder.
	 * @returns {Promise<Workspace>} Initialized Workspace instance.
	 */
	static create(vaultRoot: string): Promise<Workspace>;
	/**
	 * Loads and hydrates the workspace layout tree from `.resin/workspace.json` or falls back to default.
	 */
	private loadLayout;
	/**
	 * Serializes the current workspace layout tree into a persistent JSON structure.
	 */
	serialize(): {
		left: any;
		main: {
			id: string;
			direction: "horizontal" | "vertical";
			sizes: import("react-resizable-panels").Layout;
			children: any[];
		};
		right: any;
		tabHistory: any[];
	};
	toJSON(): {
		left: any;
		main: {
			id: string;
			direction: "horizontal" | "vertical";
			sizes: import("react-resizable-panels").Layout;
			children: any[];
		};
		right: any;
		tabHistory: any[];
	};
	/**
	 * Writes the current workspace layout to `.resin/workspace.json`.
	 */
	saveLayout(): Promise<void>;
	/**
	 * Requests a debounced layout save operation.
	 *
	 * @param {number} [delay=400] - Debounce timeout in milliseconds.
	 */
	requestSaveLayout(delay?: number): void;
	/**
	 * Returns references to the three top-level workspace split containers.
	 */
	getLayout(): {
		left: WorkspaceSplitSide;
		main: WorkspaceSplit;
		right: WorkspaceSplitSide;
	};
	/**
	 * Recursively finds all leaves matching a specific view type across the entire workspace.
	 *
	 * @param {string} type - View type string (e.g. 'editor', 'file-explorer').
	 * @returns {WorkspaceLeaf[]} List of matching leaves.
	 */
	getLeavesOfType(type: string): WorkspaceLeaf[];
	/**
	 * Discovers the parent `WorkspaceTabs` container holding a given `WorkspaceLeaf`.
	 *
	 * @param {WorkspaceLeaf} leaf - Target leaf instance.
	 * @returns {WorkspaceTabs | null} Parent tabs container or null if unattached.
	 */
	findTabsByLeaf(leaf: WorkspaceLeaf): WorkspaceTabs | null;
	/**
	 * Finds a leaf anywhere in the workspace layout tree by its unique ID.
	 *
	 * @param {string} id - Leaf unique identifier.
	 * @returns {WorkspaceLeaf | null} Found leaf or null.
	 */
	findLeafById(id: string): WorkspaceLeaf | null;
	/**
	 * Creates a new blank tab in the specified tabs group ID.
	 */
	createLeafInPanel(id: string): WorkspaceLeaf | null;
	/**
	 * Creates and mounts a new leaf in the main central area.
	 *
	 * @param {string} [type='empty'] - View type to initialize the leaf with.
	 * @param {any} [state={}] - Initial view state.
	 * @returns {WorkspaceLeaf} Created leaf instance.
	 */
	createLeafInMain(type?: string, state?: any): WorkspaceLeaf;
	/**
	 * Opens a file into an editor leaf.
	 *
	 * Intelligently selects or creates the appropriate leaf:
	 * 1. If a specific `options.leaf` is provided, replaces that leaf in-place.
	 * 2. If the file is already open in any leaf, switches active focus to that leaf.
	 * 3. If the active tab in the target split is a blank `'empty'` tab, reuses it.
	 * 4. Otherwise creates a new editor tab in the target split area.
	 *
	 * @param {string} path - Relative vault file path.
	 * @param {OpenFileOptions} [options={}] - Custom target or split options.
	 * @returns {Promise<WorkspaceLeaf>} The leaf holding the opened note editor.
	 */
	openFile(path: string, options?: OpenFileOptions): Promise<WorkspaceLeaf>;
	/**
	 * Ensures a leaf is visible and active:
	 * - Checks whether the leaf is in the left or right sidebar.
	 * - If the parent sidebar is collapsed, expands it.
	 * - Activates the tab in its parent WorkspaceTabs.
	 * - Sets the leaf as the active workspace leaf.
	 *
	 * @param {WorkspaceLeaf} leaf - Leaf to reveal.
	 */
	revealLeaf(leaf: WorkspaceLeaf): void;
	/**
	 * Finds or creates a leaf for a given view type and reveals it.
	 * If the leaf is located in a collapsed sidebar, expands the sidebar.
	 *
	 * @param {string} type - View type string (e.g. 'file-explorer', 'bookmarks-explorer').
	 * @param {'left' | 'right' | 'main'} [defaultSplit='left'] - Split to create leaf in if not found.
	 * @returns {WorkspaceLeaf} The revealed leaf.
	 */
	revealView(type: string, defaultSplit?: "left" | "right" | "main"): WorkspaceLeaf;
	/**
	 * Removes a leaf from its parent tab group and saves layout state.
	 *
	 * @param {string} id - Leaf unique identifier.
	 */
	removeLeaf(id: string): void;
}
export interface FileStats {
	ctime: number;
	mtime: number;
	size: number;
}
export declare abstract class TAbstractFile {
	vault: Vault;
	path: string;
	name: string;
	parent: TFolder | null;
	constructor(vault: Vault, path: string, parent?: TFolder | null);
}
export declare class TFile extends TAbstractFile {
	stat: FileStats;
	get basename(): string;
	get extension(): string;
}
export declare class TFolder extends TAbstractFile {
	children: TAbstractFile[];
	isRoot(): boolean;
}
export interface LinkRecord {
	id: number;
	from_path: string;
	to_path: string | null;
	to_raw: string;
	display_text: string | null;
	is_resolved: boolean;
	line: number | null;
}
/**
 * @file DataAdapter.ts
 * @description Storage abstraction contract for low-level file system I/O.
 * Matches Obsidian's DataAdapter API architecture.
 */
export interface FileStat {
	size: number;
	mtime: number;
	ctime: number;
	isDirectory: boolean;
}
export interface DataAdapter {
	/** Returns the human-readable adapter type name (e.g. 'FileSystemAdapter') */
	getName(): string;
	/** Returns the root base path for this adapter */
	getBasePath(): string;
	/** Checks if a file or directory exists on disk */
	exists(normalizedPath: string): Promise<boolean>;
	/** Reads text content from disk */
	read(normalizedPath: string): Promise<string>;
	/** Writes text content to disk, automatically creating parent directories */
	write(normalizedPath: string, data: string): Promise<void>;
	/** Writes binary content to disk, automatically creating parent directories */
	writeBinary(normalizedPath: string, data: Uint8Array): Promise<void>;
	/** Appends text content to a file on disk */
	append(normalizedPath: string, data: string): Promise<void>;
	/** Renames or moves a file or directory on disk */
	rename(oldPath: string, newPath: string): Promise<void>;
	/** Permanently deletes a file or directory from disk */
	remove(normalizedPath: string): Promise<void>;
	/** Moves a file or directory to the OS recycle bin/trash */
	trash(normalizedPath: string): Promise<void>;
	/** Creates a directory recursively */
	mkdir(normalizedPath: string): Promise<void>;
	/** Returns file metadata statistics or null if not found */
	stat(normalizedPath: string): Promise<FileStat | null>;
	/** Lists child entry names within a directory */
	list(normalizedPath?: string): Promise<string[]>;
}
export declare class FileSystemAdapter implements DataAdapter {
	private readonly basePath;
	constructor(basePath: string);
	getName(): string;
	getBasePath(): string;
	resolve(relativePath: string): string;
	private normalize;
	exists(normalizedPath: string): Promise<boolean>;
	read(normalizedPath: string): Promise<string>;
	write(normalizedPath: string, data: string): Promise<void>;
	writeBinary(normalizedPath: string, data: Uint8Array): Promise<void>;
	append(normalizedPath: string, data: string): Promise<void>;
	rename(oldPath: string, newPath: string): Promise<void>;
	remove(normalizedPath: string): Promise<void>;
	trash(normalizedPath: string): Promise<void>;
	mkdir(normalizedPath: string): Promise<void>;
	stat(normalizedPath: string): Promise<FileStat | null>;
	list(normalizedPath?: string): Promise<string[]>;
}
export interface MediaResolution {
	raw: string;
	target: string;
	resolvedPath?: string;
	fullDiskPath?: string;
	src?: string;
	width?: number;
	height?: number;
	altText?: string;
	caption?: string;
	align?: "left" | "right" | "center";
	exists: boolean;
	isExternal: boolean;
	file?: TFile | null;
}
export interface WikilinkResolution {
	/** Clean relative vault path (e.g. "work/Project Roadmap.md" or "My Note.md") */
	path: string;
	/** Resolved TFile node if file exists in the vault VFS, null otherwise */
	file: TFile | null;
	/** True if the target note exists in the vault */
	exists: boolean;
	/** Target heading if specified (e.g. "Architecture" in "[[Note#Architecture]]") */
	heading?: string;
	/** Custom alias/display text if specified (e.g. "Roadmap" in "[[Project#Architecture|Roadmap]]") */
	alias?: string;
	/** Clean display text for the link pill in UI */
	displayText: string;
}
export declare class Vault extends Events {
	/** Normalized absolute path to the root of the vault directory (forward slashes) */
	private root;
	/** Storage data adapter handling all physical disk I/O operations */
	readonly adapter: DataAdapter;
	/** Reference to central App instance */
	app?: App;
	/** In-memory lookup map of all active files and folders (keyed by normalized relative path) */
	private fileMap;
	/** Fast O(1) in-memory index of lowercase note basenames to TFile nodes */
	private basenameMap;
	/** Root directory node */
	readonly rootFolder: TFolder;
	constructor(vaultRoot: string, adapter?: DataAdapter);
	/**
	 * Returns the normalized absolute root path of the active vault.
	 */
	getRoot(): string;
	/**
	 * Returns the vault directory basename (e.g. "Resin_Vault").
	 */
	getName(): string;
	/**
	 * Resolves a vault-relative path into an absolute file-system path.
	 *
	 * @param {string} relativePath - Path relative to the vault root (e.g. 'notes/daily.md').
	 * @returns {string} Absolute normalized path.
	 */
	resolvePath(relativePath: string): string;
	/**
	 * Normalizes relative paths to forward slashes with no leading or trailing slashes.
	 */
	normalizePath(p: string): string;
	/**
	 * Retrieves any file or folder by its relative path from the in-memory VFS.
	 */
	getAbstractFileByPath(path: string): TAbstractFile | null;
	/**
	 * Retrieves a file node by path. Returns null if not found or if the entity is a directory.
	 */
	getFileByPath(path: string): TFile | null;
	/**
	 * Retrieves a folder node by path. Returns null if not found or if the entity is a file.
	 */
	getFolderByPath(path: string): TFolder | null;
	/**
	 * Retrieves all loaded files and folders in the vault.
	 */
	getAllLoadedFiles(): TAbstractFile[];
	/**
	 * Retrieves all files in the vault.
	 */
	getFiles(): TFile[];
	/**
	 * Retrieves all Markdown (*.md) files in the vault.
	 */
	getMarkdownFiles(): TFile[];
	/**
	 * Checks whether a file or folder exists in the in-memory VFS (or on disk).
	 */
	exists(path: string): Promise<boolean>;
	/**
	 * Resolves a Wikilink string (`[[Target]]`, `[[Target#Heading]]`, `[[Target|Alias]]`, `[[#Heading]]`)
	 * to a concrete vault path and TFile node.
	 *
	 * Resolution hierarchy (Obsidian-compatible):
	 * 1. If target is empty (`[[#Heading]]`), targets the current source note.
	 * 2. Exact path match in vault (e.g. "folder/Note.md").
	 * 3. Relative to source note's folder (e.g. current folder has "Note.md").
	 * 4. Basename/stem match across any directory in the entire vault.
	 *
	 * @param {string} rawLinkText - Inner wikilink text (e.g. "My Note#Architecture|System Overview")
	 * @param {string} [sourcePath] - Relative path of the note containing the wikilink
	 * @returns {WikilinkResolution} Fully resolved wikilink metadata
	 */
	resolveWikilink(rawLinkText: string, sourcePath?: string): WikilinkResolution;
	/**
	 * Checks if a file path or extension belongs to a supported image/media format.
	 */
	isMediaFile(pathOrExt: string): boolean;
	/**
	 * Resolves a media link (`![[image.png|300]]` or standard markdown `![alt](path)`)
	 * to an asset URL ready for <img> rendering.
	 */
	resolveMediaLink(rawLinkText: string, sourcePath?: string, explicitAlt?: string): MediaResolution;
	/**
	 * Retrieves all backlinks (notes linking to this note) from the SQLite index.
	 *
	 * @param {string} path - Target relative note path
	 * @returns {Promise<LinkRecord[]>} Array of backlink records
	 */
	getBacklinks(path: string): Promise<LinkRecord[]>;
	/**
	 * Universal sequence collision-free name allocator.
	 * Finds the smallest non-colliding path (e.g. "Untitled.md", "Untitled 1.md", "New Folder", "New Folder 1").
	 *
	 * @param {string} baseName - Base name (e.g. 'Untitled', 'New Folder', 'Note copy')
	 * @param {string} ext - Extension (e.g. 'md' or empty for folders)
	 * @param {string} folderPath - Target directory path
	 * @returns {string} Clean, collision-free relative path
	 */
	getNextAvailablePath(baseName?: string, ext?: string, folderPath?: string): string;
	/**
	 * Optimistically creates a new file in the in-memory VFS, emits `file:created` in **0ms**,
	 * and writes the content to disk asynchronously.
	 *
	 * @param {string} path - Target relative file path.
	 * @param {string} data - Initial file content.
	 * @returns {Promise<TFile>} Initialized TFile node.
	 */
	create(path: string, data: string): Promise<TFile>;
	/**
	 * Optimistically creates a new binary file in the in-memory VFS, emits `file:created` in 0ms,
	 * and writes the binary content to disk asynchronously.
	 *
	 * @param {string} path - Target relative file path.
	 * @param {Uint8Array} data - Binary file content.
	 * @returns {Promise<TFile>} Initialized TFile node.
	 */
	createBinary(path: string, data: Uint8Array): Promise<TFile>;
	/**
	 * Optimistically creates a folder in the in-memory VFS, emits `folder:created` in **0ms**,
	 * and creates directory on disk asynchronously.
	 */
	createFolder(path: string): Promise<TFolder>;
	/**
	 * Optimistically renames or moves a file/folder in memory, updates backlinks across referencing notes,
	 * emits `file:renamed` in **0ms**, and renames on disk asynchronously.
	 */
	rename(oldPath: string, newPath: string): Promise<void>;
	/**
	 * Updates all wikilinks referencing oldPath to newPath across the entire vault.
	 */
	private updateBacklinksForRename;
	/**
	 * Duplicates a file (or folder) using sequence collision-free name allocation (`getNextAvailablePath`).
	 * Reads original content, allocates a unique non-colliding destination path, and creates the clone.
	 *
	 * @param {string} sourcePath - Relative path to duplicate
	 * @returns {Promise<TFile | TFolder>} The duplicated file or folder node
	 */
	duplicate(sourcePath: string): Promise<TFile | TFolder>;
	/**
	 * Optimistically deletes/trashes a file or folder from memory, emits `file:deleted` in **0ms**,
	 * and sends to OS Recycle Bin asynchronously.
	 */
	trash(path: string): Promise<void>;
	/**
	 * Reconciles an external file or folder creation from the OS file watcher.
	 */
	onExternalCreated(relPath: string): Promise<void>;
	/**
	 * Reconciles an external file or folder deletion from the OS file watcher.
	 * Recursively purges all children if a folder is deleted.
	 */
	onExternalDeleted(relPath: string): void;
	/**
	 * Deletes a file or directory (alias for trash).
	 */
	remove(path: string): Promise<void>;
	/**
	 * Optimistically writes or overwrites file content, updating in-memory stats
	 * and emitting `file:modified` / `file:created`.
	 */
	write(path: string, content: string): Promise<void>;
	/**
	 * Reads file content from disk.
	 */
	read(path: string): Promise<string>;
	/**
	 * Lists direct child filenames in a directory.
	 */
	list(path?: string): Promise<string[]>;
	/**
	 * Recursively discovers all files in the vault.
	 */
	listRecursive(): Promise<string[]>;
	/**
	 * Recursively discovers all folders in the vault.
	 */
	listAllFolders(): Promise<string[]>;
	/**
	 * Reveals a file or directory in native OS file explorer.
	 */
	showInFolder(path?: string): Promise<void>;
	/**
	 * Instant 1-shot in-memory VFS population on startup.
	 * Leverages native Rust indexer / SQLite cache to build the full tree in ~12ms without IPC flooding.
	 */
	populateTree(): Promise<void>;
	/**
	 * Reconciles the in-memory VFS with the SQLite index.
	 * Dynamically adds any newly discovered files and emits file:created events
	 * so FileExplorer and tabs update in real time without restarting the app.
	 */
	syncFromIndex(): Promise<void>;
	private getParentPath;
	/**
	 * Appends or updates a child node in a parent folder, preventing duplicate entries.
	 */
	private addChildNode;
	private getOrCreateFolderNode;
	private updateDescendantPaths;
	private writeDiskFile;
	/**
	 * Asynchronously constructs and returns an initialized Vault instance with populated VFS.
	 */
	static create(vaultRoot: string): Promise<Vault>;
}
export interface Loc {
	line: number;
	col: number;
	offset: number;
}
export interface Pos {
	start: Loc;
	end: Loc;
}
export interface HeadingCache {
	heading: string;
	level: number;
	position: Pos;
	/** @deprecated Line number shorthand for backward compatibility */
	line?: number;
}
export interface LinkCache {
	link: string;
	original: string;
	displayText?: string;
	position: Pos;
}
export interface EmbedCache {
	link: string;
	original: string;
	displayText?: string;
	position: Pos;
}
export interface TagCache {
	tag: string;
	position: Pos;
}
export interface SectionCache {
	type: "paragraph" | "heading" | "code" | "list" | "blockquote" | "callout" | "table" | "thematicBreak" | "math" | "yaml" | "html";
	position: Pos;
	id?: string;
}
export interface BlockCache {
	id: string;
	section: SectionCache;
	position: Pos;
}
export interface ListItemCache {
	position: Pos;
	parent: number;
	task?: string;
}
export interface TaskCache {
	position: Pos;
	line: number;
	filePath: string;
	fileName: string;
	status: "empty" | "pending" | "done" | "canceled";
	rawChar: string;
	title: string;
	raw: string;
	due?: string;
	scheduled?: string;
	created?: string;
	completed?: string;
	priority?: "highest" | "high" | "medium" | "low" | "lowest";
	recurrence?: string;
	estimate?: string;
	project?: string;
	tags: string[];
	isTask: boolean;
}
export interface CachedMetadata {
	frontmatter?: Record<string, any>;
	frontmatterPosition?: Pos;
	headings?: HeadingCache[];
	tags?: TagCache[];
	links?: LinkCache[];
	embeds?: EmbedCache[];
	sections?: SectionCache[];
	blocks?: Record<string, BlockCache>;
	listItems?: ListItemCache[];
	tasks?: TaskCache[];
	updatedAt: number;
}
export declare class MetadataCache extends Events {
	private fileCache;
	private cacheStats;
	private tagIndex;
	private forwardLinks;
	private backwardLinks;
	private fileTags;
	private fileLinks;
	private isIndexing;
	private isSaving;
	private saveTimer;
	private vaultRef;
	app: any;
	/**
	 * Retrieves parsed metadata for a given file path.
	 */
	getFileCache(path: string): CachedMetadata | null;
	/**
	 * Retrieves all indexed tasks across the vault directly from memory (0ms).
	 */
	getTasks(filter?: {
		onlyTasks?: boolean;
		status?: string;
		search?: string;
	}): TaskCache[];
	/**
	 * Retrieves all unique tags indexed across the vault.
	 */
	getTags(): string[];
	/**
	 * Retrieves all file paths containing a specific tag.
	 */
	getFilesWithTag(tag: string): string[];
	/**
	 * Retrieves all source notes that link TO the target path (backlinks).
	 */
	getBacklinks(targetPath: string): string[];
	/**
	* Retrieves the full forward link mapping across all notes in the vault.
	* Map<sourcePath, Map<targetPath, count>>
	*/
	getResolvedLinks(): Map<string, Map<string, number>>;
	/**
	 * Parses raw markdown text and updates in-memory cache for a single note.
	 */
	updateFile(path: string, content: string, stat?: {
		mtime: number;
		size: number;
	}): CachedMetadata;
	/**
	 * Removes a file from all indexes upon deletion in O(1) complexity.
	 */
	removeFile(path: string): void;
	/**
	 * Handles note renaming across all indexes.
	 */
	renameFile(oldPath: string, newPath: string): void;
	/**
	 * Fast incremental vault cache build on startup.
	 * Hydrates from `.resin/metadata-cache.json` in ~5ms, then only indexes new/modified files.
	 *
	 * Non-blocking design:
	 * - Toast appears immediately before any I/O starts
	 * - Files are read CONCURRENTLY (not sequentially) within each batch
	 * - UI thread yields between batches via setTimeout(0)
	 * - saveToDisk() is deferred via requestIdleCallback to avoid post-index freeze
	 */
	buildCache(vault: Vault, onProgress?: (current: number, total: number, path: string) => void): Promise<void>;
	private requestSave;
	/**
	 * Atomically serializes in-memory cache to `<vault>/.resin/metadata-cache.json`.
	 */
	saveToDisk(): Promise<void>;
	/**
	 * O(1) tag re-indexing: deletes only this note's previous tags and inserts new ones.
	 */
	private reindexTags;
	/**
	 * O(1) link re-indexing: deletes only this note's previous backlinks and inserts new ones.
	 */
	private reindexLinks;
	private normalizePath;
}
/**
 * @file Settings.types.ts
 * @description Type contracts and defaults for Resin core and plugin settings.
 */
export interface CoreSettings {
	vimMode: boolean;
	theme: "dark" | "light" | "system";
	accentColor: string;
	fontSize: number;
	inlineNoteTitle: boolean;
	centeredNoteBody: boolean;
	tabTitleBar: boolean;
	showRibbon: boolean;
	lineNumbers: boolean;
	tabSize: number;
	autoPairBrackets: boolean;
	autoPairMarkdown: boolean;
	themeId: string;
	enabledSnippets: string[];
	editorFontFamily: string;
	monoFontFamily: string;
	interfaceFontFamily: string;
	spellcheck: boolean;
	confirmFileDelete: boolean;
	newFileLocation: "root" | "current";
	showIndentGuides: boolean;
}
export declare abstract class PluginSettingTab {
	app: AppAPI;
	plugin: Plugin$1;
	containerEl: HTMLElement;
	/** Unique tab identifier */
	id: string;
	/** Display title shown in settings sidebar */
	name: string;
	/** Phosphor icon name */
	icon?: string;
	/** Priority number for ordering (lower number = higher priority, e.g. 10 before 100) */
	priority: number;
	constructor(app: AppAPI, plugin: Plugin$1);
	/**
	 * Invoked when the settings tab is selected in the settings modal.
	 * Plugins populate `this.containerEl` with `Setting` instances.
	 */
	abstract display(): void;
	/**
	 * Invoked when navigating away from this settings tab.
	 */
	hide(): void;
}
export declare class SettingsManager extends Events {
	private vaultRoot;
	private configPath;
	private settings;
	private saveTimer;
	private settingTabs;
	constructor(vaultRoot: string);
	/**
	 * Initializes settings by reading .resin/config.json from disk or creating defaults.
	 */
	load(): Promise<void>;
	/**
	 * Applies CSS variables to documentElement based on current settings.
	 */
	applyCssProperties(): void;
	/**
	 * Retrieves a single core setting.
	 */
	get<K extends keyof CoreSettings>(key: K): CoreSettings[K];
	/**
	 * Retrieves full snapshot of core settings.
	 */
	getAll(): CoreSettings;
	/**
	 * Mutates a setting, updates CSS custom properties where appropriate,
	 * emits a reactive event, and debounces disk persistence.
	 */
	set<K extends keyof CoreSettings>(key: K, value: CoreSettings[K]): void;
	/**
	 * Registers a plugin settings tab.
	 */
	registerSettingTab(tab: PluginSettingTab): void;
	/**
	 * Unregisters a plugin settings tab.
	 */
	unregisterSettingTab(tab: PluginSettingTab): void;
	/**
	 * Returns all active plugin settings tabs.
	 */
	getSettingTabs(): PluginSettingTab[];
	/**
	 * Returns all active plugin settings tabs sorted by priority (ascending) and then alphabetically.
	 */
	getSortedSettingTabs(): PluginSettingTab[];
	/**
	 * Debounces disk write to avoid thrashing on rapid slider/input events.
	 */
	private requestSave;
	/**
	 * Writes current settings payload to .resin/config.json.
	 */
	save(): Promise<void>;
}
export interface ThemeManifest {
	id: string;
	name: string;
	version?: string;
	author?: string;
	description?: string;
	minAppVersion?: string;
}
export interface CustomTheme {
	manifest: ThemeManifest;
	cssContent: string;
	dirPath: string;
}
export interface CssSnippet {
	name: string;
	filename: string;
	cssContent: string;
	path: string;
}
declare class CustomStyleManager extends Events {
	private vaultRoot;
	private themesDir;
	private snippetsDir;
	private activeThemeId;
	private enabledSnippets;
	private loadedThemes;
	private loadedSnippets;
	constructor(vaultRoot: string);
	/**
	 * Initializes style manager directories and loads themes & snippets.
	 */
	init(themeId?: string, enabledSnippets?: string[]): Promise<void>;
	/**
	 * Ensures `<vault>/.resin/themes` and `<vault>/.resin/snippets` directories exist.
	 */
	ensureDirectories(): Promise<void>;
	/**
	 * Scans `<vault>/.resin/themes` for subdirectories containing manifest.json and theme.css.
	 */
	scanThemes(): Promise<CustomTheme[]>;
	/**
	 * Scans `<vault>/.resin/snippets` for *.css files.
	 */
	scanSnippets(): Promise<CssSnippet[]>;
	getThemes(): CustomTheme[];
	getSnippets(): CssSnippet[];
	getActiveThemeId(): string;
	getEnabledSnippets(): string[];
	/**
	 * Applies the theme stylesheet to document head.
	 */
	applyActiveTheme(themeId: string): void;
	/**
	 * Synchronizes all snippet style tags in document head with currently enabled snippets.
	 */
	applySnippets(enabledList?: string[]): void;
	/**
	 * Returns themes folder path.
	 */
	getThemesPath(): string;
	/**
	 * Returns snippets folder path.
	 */
	getSnippetsPath(): string;
	/**
	 * Called when a file in the vault is created, modified, or deleted.
	 * If it touches .resin/snippets or .resin/themes, updates the DOM in real time.
	 */
	handleFileEvent(relPath: string): Promise<void>;
}
export interface RibbonItemDef {
	/** Unique item identifier */
	id: string;
	/** Hover tooltip text */
	tooltip: string;
	/** Phosphor icon name */
	icon: string;
	/** Click action handler */
	handler: () => void;
}
declare class Ribbon extends Events {
	private _items;
	/**
	 * Adds or updates a ribbon item and emits `ribbon:updated`.
	 *
	 * @param {RibbonItemDef} item - Ribbon item descriptor.
	 */
	add(item: RibbonItemDef): void;
	/**
	 * Updates fields of an existing ribbon item by ID.
	 *
	 * @param {string} id - Item unique identifier.
	 * @param {Partial<RibbonItemDef>} updates - Property patch.
	 */
	update(id: string, updates: Partial<RibbonItemDef>): void;
	/**
	 * Removes a ribbon item by its ID.
	 *
	 * @param {string} id - Item unique identifier.
	 */
	remove(id: string): void;
	/**
	 * Returns a copy of all currently registered ribbon items.
	 */
	getItems(): RibbonItemDef[];
}
export type MenuSeparator = {
	type: "separator";
};
export type MenuAction = {
	type?: "action";
	id?: string;
	label: string;
	icon?: string;
	shortcut?: string;
	danger?: boolean;
	disabled?: boolean;
	onSelect: () => void;
};
export type MenuSubmenu = {
	type: "submenu";
	label: string;
	icon?: string;
	disabled?: boolean;
	items: MenuItem[];
};
export type MenuItem = MenuSeparator | MenuAction | MenuSubmenu;
export type MenuItemProvider<T = any> = (context: T) => MenuItem[] | MenuItem | null | undefined;
declare class ContextMenuRegistry extends Events {
	private providers;
	/**
	 * Registers a menu item provider for a given scope.
	 * The provider function can return a single `MenuItem`, an array of `MenuItem[]`, or null/undefined to omit.
	 *
	 * @template T - Context data type passed to the provider.
	 * @param {string} scope - Context menu scope string (e.g. 'tab:header', 'file-explorer:file').
	 * @param {MenuItemProvider<T>} provider - Provider callback.
	 * @returns {() => void} Unsubscribe function to remove the provider.
	 */
	register<T = any>(scope: string, provider: MenuItemProvider<T>): () => void;
	/**
	 * Alias for `register` provider.
	 */
	registerScopeProvider<T = any>(scope: string, provider: MenuItemProvider<T>): () => void;
	/**
	 * Resolves and aggregates all menu items for a scope given context payload and optional base items.
	 *
	 * @template T - Context data type.
	 * @param {string} scope - Context menu scope string.
	 * @param {T} context - Target context payload.
	 * @param {MenuItem[]} [baseItems=[]] - Initial component-provided menu items.
	 * @returns {MenuItem[]} Combined list of menu items.
	 */
	getItems<T = any>(scope: string, context: T, baseItems?: MenuItem[]): MenuItem[];
	/**
	 * Imperatively shows a context menu at the specified screen coordinates,
	 * resolving scoped providers through the registry.
	 */
	show<T = any>(options: ContextMenuShowOptions<T>): void;
	/**
	 * Imperatively closes any active context menu across the application.
	 */
	close(): void;
}
export interface ContextMenuShowOptions<T = any> {
	x: number;
	y: number;
	scope?: string;
	context?: T;
	items?: MenuItem[] | (() => MenuItem[]);
	onClose?: () => void;
}
export type ToastType = "info" | "success" | "warning" | "error" | "loading";
export interface ToastAction {
	label: string;
	onClick: () => void;
	variant?: "default" | "primary";
}
export interface ToastOptions {
	id?: string;
	title?: string;
	message?: string;
	type?: ToastType;
	duration?: number;
	action?: ToastAction;
	icon?: string;
	dismissable?: boolean;
	/** Progress percentage (0 - 100). When provided, renders a progress bar. */
	progress?: number;
}
export interface ToastHandle {
	/** Unique toast ID */
	id: string;
	/** Update the toast's content in-place without showing a new notification */
	update(opts: Partial<ToastOptions>): void;
	/** Dismiss this toast immediately */
	dismiss(): void;
}
export interface ToastItem extends Required<Omit<ToastOptions, "action" | "icon" | "title" | "message" | "dismissable" | "progress">> {
	id: string;
	title?: string;
	message?: string;
	action?: ToastAction;
	icon?: string;
	dismissable?: boolean;
	progress?: number;
	createdAt: number;
}
declare class ToastManager extends Events {
	private toasts;
	private counter;
	/**
	 * Returns all active toast notifications.
	 */
	getToasts(): ToastItem[];
	/**
	 * Displays a toast notification and returns a handle for updating or dismissing it.
	 *
	 * @param {ToastOptions | string} options - Toast configuration or plain message string
	 * @returns {ToastHandle} Handle with update() and dismiss() methods
	 */
	show(options: ToastOptions | string): ToastHandle;
	/**
	 * Updates a toast's content in-place — no flicker, no new toast shown.
	 * Useful for long-running operations that want to report progress.
	 *
	 * @param {string} id - Toast ID to update
	 * @param {Partial<ToastOptions>} updates - Fields to merge into the existing toast
	 */
	update(id: string, updates: Partial<ToastOptions>): void;
	/**
	 * Helper: Success toast.
	 */
	success(message: string, options?: Omit<ToastOptions, "message" | "type">): ToastHandle;
	/**
	 * Helper: Info toast.
	 */
	info(message: string, options?: Omit<ToastOptions, "message" | "type">): ToastHandle;
	/**
	 * Helper: Warning toast.
	 */
	warning(message: string, options?: Omit<ToastOptions, "message" | "type">): ToastHandle;
	/**
	 * Helper: Error toast.
	 */
	error(message: string, options?: Omit<ToastOptions, "message" | "type">): ToastHandle;
	/**
	 * Helper: Persistent loading toast (stays until dismissed).
	 */
	loading(message: string, options?: Omit<ToastOptions, "message" | "type">): ToastHandle;
	/**
	 * Helper: Binds a promise to a loading -> success / error toast sequence.
	 */
	promise<T>(promise: Promise<T>, messages: {
		loading: string;
		success: string | ((data: T) => string);
		error: string | ((err: any) => string);
	}): Promise<T>;
	/**
	 * Dismisses a toast by its ID.
	 *
	 * @param {string} id - Toast ID to remove
	 */
	dismiss(id: string): void;
	/**
	 * Dismisses all active toasts.
	 */
	dismissAll(): void;
}
export type BannerType = "info" | "warning" | "error" | "success";
export interface BannerAction {
	label: string;
	onClick: () => void;
	variant?: "primary" | "ghost";
}
export interface BannerOptions {
	id?: string;
	title: string;
	description?: string;
	type?: BannerType;
	progress?: number;
	actions?: BannerAction[];
	dismissable?: boolean;
	icon?: string;
	onDismiss?: () => void;
}
export interface BannerItem extends Required<Omit<BannerOptions, "description" | "progress" | "actions" | "icon" | "onDismiss">> {
	id: string;
	description?: string;
	progress?: number;
	actions?: BannerAction[];
	icon?: string;
	onDismiss?: () => void;
	createdAt: number;
}
export interface BannerHandle {
	id: string;
	update: (updates: Partial<Omit<BannerOptions, "id">>) => void;
	dismiss: () => void;
}
declare class BannerManager extends Events {
	private banners;
	private counter;
	/**
	 * Returns all active top notification banners.
	 */
	getBanners(): BannerItem[];
	/**
	 * Shows a top banner notification.
	 *
	 * @param {BannerOptions} options - Banner options
	 * @returns {BannerHandle} Controller to update or dismiss the banner
	 */
	show(options: BannerOptions): BannerHandle;
	/**
	 * Dismisses a banner by its ID.
	 */
	dismiss(id: string): void;
	/**
	 * Dismisses all active banners.
	 */
	dismissAll(): void;
}
export type DialogSize = "sm" | "md" | "lg" | "full";
export interface DialogButton {
	label: string;
	variant?: "primary" | "secondary" | "danger" | "ghost";
	onClick?: (handle: DialogHandle) => void | boolean | Promise<void | boolean>;
	autoFocus?: boolean;
}
export interface DialogOptions {
	id?: string;
	title?: string;
	description?: string;
	content?: ReactNode | ((handle: DialogHandle) => ReactNode);
	size?: DialogSize;
	buttons?: DialogButton[];
	closeOnBackdrop?: boolean;
	closeOnEscape?: boolean;
	checkbox?: {
		label: string;
		checked?: boolean;
		onChange?: (checked: boolean) => void;
	};
	onClose?: () => void;
}
export interface DialogInstance extends Required<Omit<DialogOptions, "title" | "description" | "content" | "buttons" | "checkbox" | "onClose">> {
	id: string;
	title?: string;
	description?: string;
	content?: ReactNode | ((handle: DialogHandle) => ReactNode);
	buttons?: DialogButton[];
	checkbox?: {
		label: string;
		checked?: boolean;
		onChange?: (checked: boolean) => void;
	};
	onClose?: () => void;
	zIndex: number;
	createdAt: number;
}
export interface DialogHandle {
	id: string;
	close: () => void;
}
declare class DialogManager extends Events {
	private stackList;
	private counter;
	constructor();
	/**
	 * Returns active dialog stack ordered from bottom to top.
	 */
	getStack(): DialogInstance[];
	/**
	 * Opens a new modal dialog.
	 *
	 * @param {DialogOptions} options - Modal options
	 * @returns {DialogHandle} Controller to close the dialog
	 */
	open(options: DialogOptions): DialogHandle;
	/**
	 * Closes a dialog by its ID.
	 */
	close(id: string): void;
	/**
	 * Closes the top-most dialog.
	 */
	closeTop(): void;
	/**
	 * Helper: Alert dialog.
	 */
	alert(message: string, title?: string): Promise<void>;
	/**
	 * Helper: Confirmation dialog.
	 */
	confirm(message: string, title?: string, options?: {
		confirmLabel?: string;
		cancelLabel?: string;
		isDanger?: boolean;
		checkbox?: {
			label: string;
			key?: string;
		};
	}): Promise<boolean>;
	/**
	 * Helper: Safe delete confirmation with "Don't show this again" option.
	 */
	confirmDelete(itemName: string, itemType: "file" | "folder" | undefined, onConfirm: () => void | Promise<void>): Promise<void>;
	/**
	 * Helper: Prompt dialog.
	 */
	prompt(message: string, defaultValue?: string, title?: string): Promise<string | null>;
}
export type StatusBarAlignment = "left" | "right";
export interface StatusBarItemOptions {
	id: string;
	alignment?: StatusBarAlignment;
	priority?: number;
	text?: string;
	icon?: string;
	tooltip?: string;
	active?: boolean;
	visible?: boolean;
	onClick?: () => void;
	render?: () => ReactNode;
}
export interface StatusBarItem extends StatusBarItemOptions {
	alignment: StatusBarAlignment;
	priority: number;
	visible: boolean;
}
export interface StatusBarItemHandle {
	id: string;
	update: (updates: Partial<Omit<StatusBarItemOptions, "id">>) => void;
	remove: () => void;
}
export interface StatusBarSnapshot {
	left: StatusBarItem[];
	right: StatusBarItem[];
}
declare class StatusBarManager extends Events {
	private items;
	private contextItems;
	private snapshot;
	private version;
	/**
	 * Version counter incremented on every state change for useSyncExternalStore.
	 */
	getVersion(): number;
	private updateSnapshot;
	/**
	 * Returns all visible status bar items for a given alignment sorted by priority.
	 */
	getItems(alignment: StatusBarAlignment): StatusBarItem[];
	/**
	 * Sets contextual status items dictated by the active view / focused leaf.
	 *
	 * @param {StatusBarItemOptions[]} items - Array of contextual status items
	 */
	setContextItems(items: StatusBarItemOptions[]): void;
	/**
	 * Clears all contextual items when a view is blurred or unmounted.
	 */
	clearContextItems(): void;
	getSnapshot(): StatusBarSnapshot;
	/**
	 * Returns active contextual status items.
	 */
	getContextItems(alignment?: StatusBarAlignment): StatusBarItem[];
	/**
	 * Registers a persistent global status bar item (from core or plugins).
	 *
	 * @param {StatusBarItemOptions} options - Item options
	 * @returns {StatusBarItemHandle} Controller to update or remove the item
	 */
	registerItem(options: StatusBarItemOptions): StatusBarItemHandle;
	/**
	 * Removes a status bar item.
	 */
	removeItem(id: string): void;
}
export interface CodeBlockContext {
	language: string;
	sourcePath?: string;
	from?: number;
	to?: number;
}
export type CodeBlockHandler = (source: string, el: HTMLElement, ctx: CodeBlockContext) => void | Promise<void>;
export interface CodeBlockRegistration {
	language: string;
	handler: CodeBlockHandler;
	pluginId?: string;
}
export declare class CodeBlockRegistry extends Events {
	private handlers;
	/**
	 * Registers a custom code block handler for a given language tag.
	 *
	 * @param {string} language - Lowercase language identifier (e.g. 'mermaid').
	 * @param {CodeBlockHandler} handler - Renderer function receiving raw source, container element, and context.
	 * @param {string} [pluginId] - Optional originating plugin ID.
	 * @returns {() => void} Cleanup function to unregister the handler.
	 */
	register(language: string, handler: CodeBlockHandler, pluginId?: string): () => void;
	/**
	 * Unregisters a code block handler.
	 */
	unregister(language: string): void;
	/**
	 * Looks up a registered handler by language tag.
	 */
	get(language: string): CodeBlockRegistration | undefined;
	/**
	 * Checks whether a handler exists for the given language tag.
	 */
	has(language: string): boolean;
	/**
	 * Returns all registered code block handlers.
	 */
	list(): CodeBlockRegistration[];
}
export interface EditorSuggestTriggerInfo {
	/** Document character offset where the trigger starts (e.g. position of '[[' or '#') */
	start: number;
	/** Document character offset of the cursor */
	end: number;
	/** The typed query string following the trigger delimiter */
	query: string;
	/** Optional stage descriptor for multi-stage suggestions (e.g. 'note', 'heading', 'alias') */
	substage?: string;
	/** Optional start offset of the current token within query for CodeMirror autocomplete filtering */
	completionStart?: number;
}
export interface EditorSuggestContext extends EditorSuggestTriggerInfo {
	editor: EditorView;
	file: TFile | null;
}
/**
 * Abstract class representing a suggestion provider in the editor.
 * Plugins and core features extend this class to provide autocompletion for
 * wikilinks, tags, slash commands, emojis, and custom macros.
 */
export declare abstract class EditorSuggest<T> {
	readonly app: App;
	constructor(app: App);
	/**
	 * Checks whether the current cursor position matches the trigger condition.
	 * Returns trigger metadata if active, or null to pass through.
	 */
	abstract onTrigger(cursor: number, view: EditorView, file: TFile | null): EditorSuggestTriggerInfo | null;
	/**
	 * Returns a list of candidate suggestions matching the trigger context.
	 */
	abstract getSuggestions(context: EditorSuggestContext): T[] | Promise<T[]>;
	/**
	 * Custom DOM renderer for a suggestion row in the dropdown popup.
	 */
	abstract renderSuggestion(value: T, el: HTMLElement): void;
	/**
	 * Called when a suggestion is selected (via Tab, Enter, or Click) to apply the change to the editor.
	 */
	abstract selectSuggestion(value: T, evt: MouseEvent | KeyboardEvent | Event, view: EditorView): void;
}
export interface ActiveSuggestMatch {
	suggest: EditorSuggest<any>;
	trigger: EditorSuggestTriggerInfo;
}
export declare class EditorSuggestRegistry {
	private suggests;
	/**
	 * Registers a new suggestion provider.
	 * Providers registered later take higher priority.
	 *
	 * @param {EditorSuggest<any>} suggest - Provider instance
	 * @returns {() => void} Teardown callback that unregisters the provider
	 */
	register(suggest: EditorSuggest<any>): () => void;
	/**
	 * Unregisters a suggestion provider.
	 */
	unregister(suggest: EditorSuggest<any>): void;
	/**
	 * Iterates through all registered providers to find the first one that matches the trigger condition.
	 */
	findTrigger(cursor: number, view: EditorView, file: TFile | null): ActiveSuggestMatch | null;
	/**
	 * Returns a snapshot of all currently registered suggest providers.
	 */
	getSuggests(): ReadonlyArray<EditorSuggest<any>>;
}
export interface CommandDefinition {
	/** Unique command identifier (e.g. 'core:open-command-palette', 'core.graph-view:open-graph-view') */
	id: string;
	/** Human-readable display label */
	label: string;
	/** Grouping category (e.g. 'Navigation', 'Editor', 'Workspace', 'Plugins') */
	category?: string;
	/** Optional descriptive explanation */
	description?: string;
	/** Default shortcut accelerator (e.g. 'Mod+Shift+G', 'Mod+N') */
	defaultShortcut?: string;
	/** Optional precondition check before execution */
	checkCallback?: () => boolean;
	/** Action executed when the command triggers */
	handler: () => void;
}
declare class KeymapManager extends Events {
	readonly app: App;
	private commands;
	private overrides;
	private isRebinding;
	private rebindingCallback;
	private unlistenGlobal;
	constructor(app: App);
	/**
	 * Registers a command into the global keymap catalog.
	 */
	registerCommand(command: CommandDefinition): () => void;
	/**
	 * Retrieves a registered command by its unique ID.
	 */
	getCommand(id: string): CommandDefinition | null;
	/**
	 * Returns all registered application commands.
	 */
	listCommands(): CommandDefinition[];
	/**
	 * Returns the active shortcut for a command (custom override or default).
	 */
	getActiveShortcut(commandId: string): string | null;
	/**
	 * Returns true if a command has been customized with a user override.
	 */
	hasOverride(commandId: string): boolean;
	/**
	 * Sets a custom keyboard shortcut override for a command.
	 * Pass `null` or empty string to unbind the command.
	 */
	setOverride(commandId: string, shortcut: string | null): Promise<void>;
	/**
	 * Resets a specific command's shortcut back to its factory default.
	 */
	resetOverride(commandId: string): Promise<void>;
	/**
	 * Resets all user hotkey customizations back to defaults.
	 */
	resetAllOverrides(): Promise<void>;
	/**
	 * Identifies all conflicting commands that share the same active shortcut.
	 */
	findConflicts(shortcut: string, excludeCommandId?: string): CommandDefinition[];
	/**
	 * Starts recording the next keystroke for interactive rebinding in Settings UI.
	 */
	startRecording(callback: (shortcut: string | null) => void): () => void;
	/**
	 * Initializes the top-level window keydown listener.
	 */
	private initGlobalListener;
	private loadOverrides;
	private saveOverrides;
	/**
	 * Cleans up listeners on shutdown.
	 */
	destroy(): void;
}
export interface RequestUrlParam {
	url: string;
	method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD";
	headers?: Record<string, string>;
	body?: string;
	timeoutMs?: number;
	pluginId?: string;
	allowLocal?: boolean;
}
export interface RequestUrlResponse {
	status: number;
	statusText: string;
	headers: Record<string, string>;
	text: string;
	ok: boolean;
	json<T = any>(): T;
}
/**
 * Executes a secure, sandboxed HTTP request via the Rust backend.
 * Enforces SSRF blocking for private subnets, timeout limits, and audit provenance.
 */
export declare function requestUrl(params: RequestUrlParam): Promise<RequestUrlResponse>;
/**
 * Scoped, sandboxed API contract provided to each plugin instance.
 */
export interface AppAPI {
	/** Reference to workspace layout engine for leaf and split queries */
	workspace: Workspace;
	/** Application-wide event bus */
	events: Events;
	/** In-memory metadata and link graph index */
	metadataCache: MetadataCache;
	/** Vault configuration and core settings manager */
	settings: SettingsManager;
	/** Central keyboard shortcut and keymap manager */
	keymap: KeymapManager;
	/** Decoupled context menu extension registry */
	contextMenu: ContextMenuRegistry;
	/** Central toast notification manager */
	toast: ToastManager;
	/** Inverted top notification banner manager */
	banners: BannerManager;
	/** Layered modal dialog manager */
	dialogs: DialogManager;
	/** Bottom status bar manager */
	statusBar: StatusBarManager;
	/**
	 * Isolated persistent JSON storage scoped to `.resin/plugins/<pluginId>/data.json`.
	 */
	storage: {
		get<T>(): Promise<T | null>;
		set<T>(data: T): Promise<void>;
	};
	/**
	 * UI registration methods for views, sidebars, blocks, ribbon icons, and context menus.
	 */
	ui: {
		registerView(type: string, creator: ViewCreator, meta?: {
			icon: string;
			title: string;
		}): void;
		unregisterView(type: string): void;
		registerSidebarPanel(id: string, creator: () => HTMLElement): void;
		registerRibbonItem(item: RibbonItemDef): void;
		removeRibbonItem(id: string): void;
		registerContextMenuItem<T = any>(scope: string, provider: MenuItemProvider<T>): () => void;
		registerSettingTab(tab: PluginSettingTab): void;
		registerCodeBlockHandler(language: string, handler: CodeBlockHandler): () => void;
		registerEditorSuggest(suggest: EditorSuggest<any>): () => void;
	};
	registerEditorSuggest(suggest: EditorSuggest<any>): () => void;
	isDarkMode(): boolean;
	/**
	 * Safe, sandboxed HTTP request client enforcing SSRF protection and audit provenance.
	 */
	request(params: RequestUrlParam): Promise<RequestUrlResponse>;
	/**
	 * Command registration and dispatch scoped to the plugin.
	 */
	commands: {
		register(id: string, label: string, handler: () => void, shortcut?: string, meta?: {
			category?: string;
			description?: string;
		}): () => void;
		execute(id: string): void;
		list(): CommandDefinition[];
	};
	/**
	 * Scoped Vault filesystem access and in-memory VFS methods.
	 */
	vault: {
		readonly adapter: DataAdapter;
		read(path: string): Promise<string>;
		write(path: string, content: string): Promise<void>;
		create(path: string, data: string): Promise<TFile>;
		createFolder(path: string): Promise<TFolder>;
		duplicate(path: string): Promise<TFile | TFolder>;
		rename(oldPath: string, newPath: string): Promise<void>;
		trash(path: string): Promise<void>;
		remove(path: string): Promise<void>;
		list(path?: string): Promise<string[]>;
		getRoot(): string;
		getName(): string;
		getNextAvailablePath(baseName?: string, ext?: string, folderPath?: string): string;
		resolveWikilink(linkText: string, sourcePath?: string): WikilinkResolution;
		getBacklinks(path: string): Promise<LinkRecord[]>;
		getAbstractFileByPath(path: string): TAbstractFile | null;
		getFileByPath(path: string): TFile | null;
		getFolderByPath(path: string): TFolder | null;
		getFiles(): TFile[];
		getMarkdownFiles(): TFile[];
		getAllLoadedFiles(): TAbstractFile[];
		readonly rootFolder: TFolder;
		on(event: string, handler: (payload: any) => void): EventRef;
		off(event: string, handler: (payload: any) => void): void;
		offref(ref: EventRef): void;
	};
}
declare class App {
	/** Active workspace layout tree */
	readonly workspace: Workspace;
	/** Active vault storage instance */
	readonly vault: Vault;
	/** In-memory metadata and link graph index */
	readonly metadataCache: MetadataCache;
	/** Vault settings and plugin settings tabs manager */
	readonly settings: SettingsManager;
	/** Custom dynamic styles, themes, and CSS snippets manager */
	readonly customStyles: CustomStyleManager;
	/** Central application event aggregator */
	readonly events: Events;
	/** Scoped context menu provider registry */
	readonly contextMenu: ContextMenuRegistry;
	/** Central toast notification manager */
	readonly toast: ToastManager;
	/** Inverted top notification banner manager */
	readonly banners: BannerManager;
	/** Layered modal dialog manager */
	readonly dialogs: DialogManager;
	/** Bottom status bar manager */
	readonly statusBar: StatusBarManager;
	/** Central keyboard shortcut and keymap manager */
	readonly keymap: KeymapManager;
	/** Registry of workspace view factories mounted into WorkspaceLeaf instances */
	readonly viewRegistry: Map<string, ViewRegistration>;
	/** Custom sidebar panel creators */
	readonly sidebarPanels: Map<string, () => HTMLElement>;
	/** Global ribbon items manager */
	readonly ribbon: Ribbon;
	/** Custom markdown code block processor registry */
	readonly codeBlocks: CodeBlockRegistry;
	/** Central editor autocompletion and suggestion provider registry */
	readonly editorSuggest: EditorSuggestRegistry;
	constructor(vault: Vault, workspace: Workspace);
	/**
	 * Closes open tabs associated with deleted files or folders.
	 */
	private handleFileDeleted;
	/**
	 * Updates paths and titles on open tabs when notes or folders are renamed.
	 */
	private handleFileRenamed;
	/**
	 * Registers a new workspace view type into the global view registry.
	 *
	 * @param {string} type - Unique view identifier (e.g. 'editor', 'file-explorer').
	 * @param {ViewCreator} creator - Factory returning a new `View` instance.
	 * @param {{ icon: string; title: string }} [meta] - Icon and default title.
	 */
	registerView(type: string, creator: ViewCreator, meta?: {
		icon: string;
		title: string;
	}): void;
	/**
	 * Unregisters a view type from the global view registry.
	 */
	unregisterView(type: string): void;
	/**
	 * Registers a custom sidebar panel creator.
	 */
	registerSidebarPanel(id: string, creator: () => HTMLElement): void;
	isDarkMode(): boolean;
	/**
	 * Registers a button on the global Ribbon navigation bar.
	 */
	/**
	 * Registers factory built-in core workspace and navigation commands.
	 */
	private registerCoreCommands;
	/**
	 * Registers a button on the global Ribbon navigation bar.
	 */
	registerRibbonItem(item: RibbonItemDef): void;
	/**
	 * Registers an executable command into the application keymap & command catalog.
	 */
	registerCommand(command: CommandDefinition): () => void;
	/**
	 * Executes a command by its registered ID.
	 */
	executeCommand(id: string): void;
	/**
	 * Reveals a file or directory in the OS file explorer (Windows Explorer / Finder).
	 */
	showInFolder(path: string): Promise<void>;
	/**
	 * Lists all currently registered application commands.
	 */
	listCommands(): CommandDefinition[];
}
declare class Plugin$1 extends Component {
	/** Unique plugin identifier (e.g. 'core.file-explorer') */
	id: string;
	/** Human-readable plugin name */
	name: string;
	/** Scoped AppAPI sandbox instance injected by the PluginLoader */
	app: AppAPI;
	private _ribbonCount;
	/**
	 * Registers a ribbon button on the left sidebar navigation bar.
	 *
	 * @param {string} icon - Phosphor icon name.
	 * @param {string} title - Tooltip title text.
	 * @param {() => void} callback - Action handler on click.
	 * @returns {RibbonItemDef} Registered ribbon item descriptor.
	 */
	addRibbonIcon(icon: string, title: string, callback: () => void): RibbonItemDef;
	addSettingTab(tab: PluginSettingTab): void;
	addCommand(command: {
		id: string;
		label: string;
		shortcut?: string;
		category?: string;
		description?: string;
		handler: () => void;
	}): () => void;
	/**
	 * Attaches Resin tooltip to any DOM element, alternatively you can add aria-label or title to element
	 * @param el HTML element to atach tooltip to
	 * @param tooltip what will be shown
	 * @param options options
	 */
	setTooltip(el: HTMLElement, tooltip: string, options?: {
		side?: "top" | "bottom" | "left" | "right";
	}): void;
	/**
	 * Registers a custom workspace view type mounted into workspace leaves.
	 *
	 * @param {string} type - Unique view type string.
	 * @param {ViewCreator} creator - View factory.
	 * @param {{ icon: string; title: string }} [meta] - Icon and default title.
	 */
	registerView(type: string, creator: ViewCreator, meta?: {
		icon: string;
		title: string;
	}): void;
	/**
	 * Registers a decoupled context menu item provider for a given scope with automatic cleanup on unload.
	 *
	 * @param {string} scope - Context menu scope string (e.g. 'tab:header', 'file-explorer:file').
	 * @param {MenuItemProvider<T>} provider - Menu item provider.
	 */
	registerContextMenu<T = any>(scope: string, provider: MenuItemProvider<T>): void;
	/**
	 * Registers a custom code block handler for markdown fenced code blocks (e.g. ```mermaid).
	 * Automatically deregistered when the plugin is unloaded.
	 *
	 * @param {string} language - Lowercase language tag identifier.
	 * @param {CodeBlockHandler} handler - Renderer function receiving source, container element, and context.
	 */
	registerCodeBlockHandler(language: string, handler: CodeBlockHandler): void;
	/**
	 * Registers a custom editor suggestion provider (autocompleter) with automatic cleanup on unload.
	 *
	 * @param {EditorSuggest<any>} suggest - Provider instance extending EditorSuggest.
	 */
	registerEditorSuggest(suggest: EditorSuggest<any>): void;
	/**
	 * Loads persistent JSON data for this plugin from `.resin/plugins/<pluginId>/data.json`.
	 */
	loadData<T>(): Promise<T | null>;
	/**
	 * Saves persistent JSON data for this plugin to `.resin/plugins/<pluginId>/data.json`.
	 */
	saveData<T>(data: T): Promise<void>;
	/**
	 * Default unload lifecycle hook: cleans up all tracked event subscriptions and registrations.
	 */
	onUnload(): Promise<void>;
}
/**
 * @file Setting.ts
 * @description Fluent builder DSL for consistent, accessible settings UI rows in Resin.
 *
 * Follows the standard pattern:
 * ```ts
 * new Setting(containerEl)
 *   .setName('Inline Title')
 *   .setDesc('Show title input inside editor canvas')
 *   .addToggle(t => t.setValue(true).onChange(val => ...))
 * ```
 */
export declare class Setting {
	settingEl: HTMLElement;
	infoEl: HTMLElement;
	nameEl: HTMLElement;
	descEl: HTMLElement;
	controlEl: HTMLElement;
	constructor(containerEl: HTMLElement);
	setName(name: string): this;
	setDesc(desc: string | DocumentFragment | HTMLElement): this;
	setHeading(): this;
	setClass(cls: string): this;
	addToggle(cb: (toggle: ToggleComponent) => void): this;
	addText(cb: (text: TextComponent) => void): this;
	addDropdown(cb: (dropdown: DropdownComponent) => void): this;
	addSlider(cb: (slider: SliderComponent) => void): this;
	addButton(cb: (btn: ButtonComponent) => void): this;
}
declare class ToggleComponent {
	inputEl: HTMLInputElement;
	labelEl: HTMLLabelElement;
	constructor(containerEl: HTMLElement);
	setValue(val: boolean): this;
	getValue(): boolean;
	onChange(cb: (val: boolean) => void): this;
	setDisabled(disabled: boolean): this;
}
declare class TextComponent {
	inputEl: HTMLInputElement;
	constructor(containerEl: HTMLElement);
	setPlaceholder(p: string): this;
	setValue(val: string): this;
	getValue(): string;
	setDisabled(disabled: boolean): this;
	onChange(cb: (val: string) => void): this;
}
declare class DropdownComponent {
	selectEl: HTMLSelectElement;
	constructor(containerEl: HTMLElement);
	addOption(value: string, label: string): this;
	setValue(val: string): this;
	getValue(): string;
	setDisabled(disabled: boolean): this;
	onChange(cb: (val: string) => void): this;
}
declare class SliderComponent {
	inputEl: HTMLInputElement;
	valueDisplay: HTMLSpanElement;
	constructor(containerEl: HTMLElement);
	setLimits(min: number, max: number, step?: number): this;
	setValue(val: number): this;
	getValue(): number;
	setDisabled(disabled: boolean): this;
	onChange(cb: (val: number) => void): this;
}
declare class ButtonComponent {
	buttonEl: HTMLButtonElement;
	constructor(containerEl: HTMLElement);
	setButtonText(text: string): this;
	setCta(): this;
	setWarning(): this;
	setDisabled(disabled: boolean): this;
	onClick(cb: () => void): this;
}

export {
	Plugin$1 as Plugin,
};

export {};
